# COMPLETION SETTINGS
# add custom completion scripts
fpath=(~/.zsh_completions $fpath) 

. ~/.oh-my-zshrc

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored
zstyle ':completion:*' matcher-list ''
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
bindkey -e
# End of lines configured by zsh-newuser-install

#screen
bindkey "^[[1~" beginning-of-line
bindkey "^[[3~" delete-char
bindkey "^[[4~" end-of-line
bindkey "^[[5~" history-beginning-search-backward
bindkey "^[[6~" history-beginning-search-forward
bindkey "^[[A"  up-history
bindkey "^[[B"  down-history
#terminator
bindkey "^[OH" beginning-of-line
bindkey "^[OF" end-of-line

setopt HIST_IGNORE_DUPS
setopt inc_append_history
setopt share_history

export PS1="%F{green}%n %F{red}%~%F{white}%(#.#.$) "
export RPROMPT="%F{grey}%T%F{white}"

. ~/.aliases
. ~/.envs
